<?php
/**
 * Created by PhpStorm.
 * User: HS
 * Date: 2017/10/2
 * Time: 23:07
 */

namespace app\admin\controller;
use think\Controller;


class Base extends Controller{

    /*
     * page
     * */
    public $page = '';
    /*
     * 每页显示多少条
     * */
    public $size ='';
    /*
     * 查询条件的起始值
     * */
    public $from = 0;

    /*
     * 定义model
     * */
    public $model = '';


    /*
     * 初始化方法
     * */
    public function  _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        //判断用户是否登入
        $isLogin = $this->isLogin();
        if (!$isLogin){
            return $this->redirect('login/index');
        }
    }
    /*
     * 判断是否登入
     * */
    public  function isLogin(){
        //获取session
        $user = session(config('admin.session_user'),'',config('admin.session_user_scope'));
        if ($user && $user->id){
            return true;
        }
        return false;
    }

    /*
     * 获取分页page size内容
     * */
    public  function  getPageAndSize($data){
        $this->page =!empty($data['page']) ? $data['page'] : 1;
        $this->size =!empty($data['size']) ? $data[size]:config('paginate.list_rows');
        $this->from = ($this->page -1) * $this->size;
    }
    /*
     * 删除逻辑
     * */
    public function delete($id = 0){
        //echo  $id;
        if (!intval($id)){
            return $this->result('',0,'ID不合法');
        }
        //用$model 是删除能够灵活的使用，比如删除表用到删除，评论也用到删除等
        //下面这一行防止控制器名和表名不一致的情况，上面需要定义全局变量
        $model = $this->model ? $this->model : request()->controller();
        // 如果是php7 则$model = $this->model ??  request()->controller();
        try{
            $res = model($model)->save(['status' => -1],['id' => $id]);
        }catch (\Exception $e){
            return $this->result('',0,$e->getMessage());
        }
        if($res){
            return $this->result(['jump_url'=>$_SERVER['HTTP_REFERER']],1,'OK');
        }else{
            $this->result('',0,'删除失败');
        }
    }

    //通用化修改逻辑
    public function status(){
        $data = input('param.');
        //tp5 validata校验，自行完成
        //通过id去库中查询记录是否存在
        //model('News')->get($data['id']);
        $model = $this->model ? $this->model : request()->controller();

        try{
            $res = model($model)->save(['status' => $data['status']],['id' => $data['id']]);
        }catch (\Exception $e){
            return $this->result('',0,$e->getMessage());
        }
        if($res){
            return $this->result(['jump_url'=>$_SERVER['HTTP_REFERER']],1,'OK');
        }else{
            $this->result('',0,'修改失败');
        }
    }

    /*
     * 通用编辑功能
     * */
    //1.id获取记录所有数据，填充模板。save([],['id'=>$id])
/*    public function editor(){
        $data = input('param.');
        $model = $this->model ? $this->model : request()->controller();
        $res = model($model)->save(['id' => $data['id']],['title'=>$data['title']]);
        //halt($res);
}*/


}





